--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dada972dev/SimpleBroadcast-for-Pmmp
build-by-default: true
branches:
- main
projects:
  SimpleBroadcast-for-Pmmp:
    path: ""
    icon: logo.png
...
